<?php

namespace AppBundle\Repository;

/**
 * AuthorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthorRepository extends \Doctrine\ORM\EntityRepository
{
    public function searchName(string $query)
    {
        $qb = $this->getEntityManager()
            ->createQuery("SELECT a FROM AppBundle:Author a WHERE a.name LIKE ?1")
            ->setParameter('1', '%'.$query.'%');
        return $qb;
    }
}
