<?php

namespace AppBundle\Repository;

/**
 * BookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookRepository extends \Doctrine\ORM\EntityRepository
{
    public function searchTitle(string $query)
    {
        $qb = $this->getEntityManager()
            ->createQuery("SELECT b FROM AppBundle:Book b WHERE b.title LIKE ?1")
            ->setParameter('1', '%'.$query.'%');

        return $qb;
    }
}
