<?php

namespace AppBundle\Repository;

/**
 * GenreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenreRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Searches for genres by on a given name
     *
     * @param string $query
     * @return \Doctrine\ORM\Query
     */
    public function searchTitle(string $query)
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('g')
            ->from('AppBundle:Genre', 'g')
            ->where('g.name LIKE ?1')
            ->setParameter('1', '%'.$query.'%')
            ->getQuery();

        return $qb;
    }
}
