worth_reading_admin:
  path: /
  defaults: { _controller: AppBundle:Admin:index }

worth_reading_admin_change_role:
  path: /change-role/{role}/{userId}
  methods: [POST]
  defaults: { _controller: AppBundle:Admin:changeRole }


